param(
    [Parameter(Mandatory=$true)][string]$Workspace,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$TemplateRoot = Join-Path $RepoRoot 'templates'

if (-not (Test-Path $Workspace)) {
    throw "Workspace not found: $Workspace"
}

$targets = @(
    @{ Src = 'plot_style.py'; Dst = '03_analysis\plot_style.py' },
    @{ Src = 'PAPER_VISUAL_STYLE.md'; Dst = '06_paper\PAPER_VISUAL_STYLE.md' },
    @{ Src = 'FIGURE_MANIFEST.md'; Dst = '06_paper\FIGURE_MANIFEST.md' }
)

New-Item -ItemType Directory -Force (Join-Path $Workspace '05_results\figures\final') | Out-Null
New-Item -ItemType Directory -Force (Join-Path $Workspace '06_paper') | Out-Null

foreach ($item in $targets) {
    $src = Join-Path $TemplateRoot $item.Src
    $dst = Join-Path $Workspace $item.Dst
    if (-not (Test-Path $src)) { throw "Template missing: $src" }
    if ((Test-Path $dst) -and -not $Force) {
        Write-Host "Keep existing: $dst" -ForegroundColor Yellow
    } else {
        Copy-Item -LiteralPath $src -Destination $dst -Force
        Write-Host "Installed: $dst" -ForegroundColor Green
    }
}

Write-Host ''
Write-Host 'PAPER-VIZ scaffold ready.' -ForegroundColor Green
Write-Host "Final figures: $(Join-Path $Workspace '05_results\figures\final')"
Write-Host "Manifest:      $(Join-Path $Workspace '06_paper\FIGURE_MANIFEST.md')"
Write-Host 'No figures were generated by this script.'
